package com.ledgerly.app.ui.theme

import androidx.compose.ui.graphics.Color

// Brand — deep pine, used as the primary editorial accent
val InkDarkPine = Color(0xFF17342B)
val EmeraldLight = Color(0xFF0F5A45)
val EmeraldDark = Color(0xFF7FE0B4)
val EmeraldTint = Color(0xFFD8EFE4)

// Semantic money colors
val IncomeGreen = Color(0xFF1E7B4E)
val IncomeGreenDark = Color(0xFF63D49A)
val ExpenseRed = Color(0xFFB43A2E)
val ExpenseRedDark = Color(0xFFF08C7D)
val AmberWarn = Color(0xFF9C6B08)
val AmberWarnDark = Color(0xFFF3C15D)

// --- Light scheme: warm ivory "paper" canvas with near-black ink ---
val LightBackground = Color(0xFFF6F2E9)
val LightSurface = Color(0xFFFFFCF5)
val LightSurfaceContainer = Color(0xFFEFE9DC)
val LightSurfaceVariant = Color(0xFFE7E0D2)
val LightOnSurface = Color(0xFF1D1A16)
val LightOnSurfaceVariant = Color(0xFF5C5649)
val LightOutline = Color(0xFF8A8376)
val LightPrimary = Color(0xFF0F5A45)
val LightOnPrimary = Color(0xFFFDFCF7)
val LightPrimaryContainer = Color(0xFFD8E9DF)
val LightOnPrimaryContainer = Color(0xFF0A2E22)
val LightSecondary = Color(0xFF57544C)
val LightOnSecondary = Color(0xFFFDFCF7)
val LightSecondaryContainer = Color(0xFFE5E2D8)
val LightOnSecondaryContainer = Color(0xFF211F1A)
val LightTertiary = Color(0xFF7A5B32)
val LightOnTertiary = Color(0xFFFDFCF7)
val LightTertiaryContainer = Color(0xFFF2E6CE)
val LightOnTertiaryContainer = Color(0xFF2B1F0A)
val LightError = Color(0xFFA33B2E)

// --- Dark scheme: deep warm charcoal, soft elevation ---
val DarkBackground = Color(0xFF14130F)
val DarkSurface = Color(0xFF1A1915)
val DarkSurfaceContainer = Color(0xFF26231D)
val DarkSurfaceContainerHigh = Color(0xFF2E2B24)
val DarkSurfaceVariant = Color(0xFF4A463C)
val DarkOnSurface = Color(0xFFECE7DC)
val DarkOnSurfaceVariant = Color(0xFFC6BFAF)
val DarkOutline = Color(0xFF918979)
val DarkPrimary = Color(0xFF7FE0B4)
val DarkOnPrimary = Color(0xFF083A2C)
val DarkPrimaryContainer = Color(0xFF1B523E)
val DarkOnPrimaryContainer = Color(0xFFB5EED2)
val DarkSecondary = Color(0xFFCCC6B8)
val DarkOnSecondary = Color(0xFF2C2A23)
val DarkSecondaryContainer = Color(0xFF44403A)
val DarkOnSecondaryContainer = Color(0xFFE7E2D4)
val DarkTertiary = Color(0xFFE0BE8B)
val DarkOnTertiary = Color(0xFF45330D)
val DarkTertiaryContainer = Color(0xFF5D4A24)
val DarkOnTertiaryContainer = Color(0xFFF9EBC7)
val DarkError = Color(0xFFFFB3A5)